nelmio_api_doc:
    documentation:
        info:
            title: "API Documentation"
            description: "Generated API documentation using OpenAPI"
            version: "1.0.0"
            
nelmio_api_doc:
    areas:
        path_patterns: # an array of regexps (document only routes under /api, except /api/doc)
            - ^/api(?!/doc$)
        host_patterns: # document only routes with a host of the form api.*
            - ^api\.

