name: Deploy Symfony to VPS

on:
  push:
    branches:
      - master # Déclenchement à chaque push sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3

    # Étape 2 : Synchroniser les fichiers avec le VPS
    - name: Deploy to VPS
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |

        echo "heheheh"

        cd ~/.ssh 
        nano balbla
