name: Deploy Symfony to VPS

on:
  push:
    branches:
      - master # Déclenchement à chaque push sur la branche master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Étape 1 : Récupérer le code
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Debug SSH connection
     env:
       SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
     run: |
       mkdir -p ~/.ssh
       echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
       chmod 600 ~/.ssh/id_rsa
       ssh-keyscan -H 46.202.153.153 >> ~/.ssh/known_hosts
       ssh -v -i ~/.ssh/id_rsa root@46.202.153.153 "echo 'Connexion SSH réussie'"