name: Deploy Symfony to VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: debian-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Sync files to VPS
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 81.51.245.32 >> ~/.ssh/known_hosts
          rsync -avz --delete --exclude=".git" ./ root@46.202.153.153:/www/wwwroot/46.202.153.153/ratrappage/

      - name: Set permissions
        run: |
          ssh -i ~/.ssh/id_rsa root@46.202.153.153 "sudo chown -R www:www /www/wwwroot/46.202.153.153/ratrappage/"

